In [1]:
import sqlite3  # py 自带的模块
# sqlite 单机关系型数据库

# 数据库文件路径（Windows 绝对路径用 r 前缀避免转义）
DB_PATH = r"C:\Users\Hester\Desktop\AI\第11周-ChatBI数据智能问答\Week12\04_SQL-Code-Agent-Demo\chinook.db"

# 连接到Chinook数据库
conn = sqlite3.connect(DB_PATH)  # 数据库文件，包含多张表

"""
sqlite vs mysql
- sqlite 单机数据库，嵌入式数据库，和编程语言集成完善，不需要额外安装软件；
- sqlite 默认是一个文件单数据库，mysql 支持 多数据库；
- sqlite 默认是本地使用，并且是单线程使用，不支持远程连接；
"""

# 创建一个游标对象
cursor = conn.cursor()

# 获取数据库中所有表的名称
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()
tables

[('albums',),
 ('sqlite_sequence',),
 ('artists',),
 ('customers',),
 ('employees',),
 ('genres',),
 ('invoices',),
 ('invoice_items',),
 ('media_types',),
 ('playlists',),
 ('playlist_track',),
 ('tracks',),
 ('sqlite_stat1',)]

In [2]:
'''数据库解析'''
from typing import Union
import traceback
from sqlalchemy import create_engine, inspect, func, select, Table, MetaData, text  # ORM 框架
import pandas as pd

class DBParser:
    '''DBParser 数据库的解析'''
    def __init__(self, db_url:str) -> None:
        '''初始化
        db_url: 数据库链接地址
        mysql: mysql://root:123456@localhost:3306/mydb?charset=utf8mb4
        sqlite: sqlite://chinook.db
        '''

        # 判断数据库类型
        if 'sqlite' in db_url:
            self.db_type = 'sqlite'
        elif 'mysql' in db_url:
            self.db_type = 'mysql'

        # 链接数据库
        self.engine = create_engine(db_url, echo=False)
        self.conn = self.engine.connect()
        self.db_url = db_url

        # 查看表明
        self.inspector = inspect(self.engine)
        self.table_names = self.inspector.get_table_names()  # 获取table信息

        self._table_fields = {}  # 数据表字段
        self.foreign_keys = []   # 数据库外键
        self._table_sample = {}  # 数据表样例

        # 依次对每张表的字段进行统计
        for table_name in self.table_names:
            print("Table ->", table_name)
            self._table_fields[table_name] = {}

            # 累计外键
            self.foreign_keys += [
                {
                    'constrained_table': table_name,
                    'constrained_columns': x['constrained_columns'],
                    'referred_table': x['referred_table'],
                    'referred_columns': x['referred_columns'],
                } for x in self.inspector.get_foreign_keys(table_name)
            ]

            # 获取当前表的字段信息
            table_instance = Table(table_name, MetaData(), autoload_with=self.engine)
            table_columns = self.inspector.get_columns(table_name)
            self._table_fields[table_name] = {x['name']: x for x in table_columns}

            # 对当前字段进行统计
            for column_meta in table_columns:
                # 获取当前字段
                column_instance = getattr(table_instance.columns, column_meta['name'])

                # 统计unique
                query = select(func.count(func.distinct(column_instance)))
                distinct_count = self.conn.execute(query).fetchone()[0]
                self._table_fields[table_name][column_meta['name']]['distinct'] = distinct_count

                # 统计most frequency value
                field_type = self._table_fields[table_name][column_meta['name']]['type']
                field_type = str(field_type)
                if 'text' in field_type.lower() or 'char' in field_type.lower():
                    query = (
                        select(column_instance, func.count().label('count'))
                        .group_by(column_instance)
                        .order_by(func.count().desc())
                        .limit(1)
                    )
                    top1_value = self.conn.execute(query).fetchone()[0]
                    self._table_fields[table_name][column_meta['name']]['mode'] = top1_value

                # 统计missing个数
                query = select(func.count()).filter(column_instance == None)
                nan_count = self.conn.execute(query).fetchone()[0]
                self._table_fields[table_name][column_meta['name']]['nan_count'] = nan_count

                # 统计max
                query = select(func.max(column_instance))
                max_value = self.conn.execute(query).fetchone()[0]
                self._table_fields[table_name][column_meta['name']]['max'] = max_value

                # 统计min
                query = select(func.min(column_instance))
                min_value = self.conn.execute(query).fetchone()[0]
                self._table_fields[table_name][column_meta['name']]['min'] = min_value

                # 任意取值
                query = select(column_instance).limit(10)
                random_value = self.conn.execute(query).all()
                random_value = [x[0] for x in random_value]
                random_value = [str(x) for x in random_value if x is not None]
                random_value = list(set(random_value))
                self._table_fields[table_name][column_meta['name']]['random'] = random_value[:3]

            # 获取表样例（第一行）
            query = select(table_instance)
            self._table_sample[table_name] = pd.DataFrame([self.conn.execute(query).fetchone()])
            self._table_sample[table_name].columns = [x['name'] for x in table_columns]

    def get_table_fields(self, table_name) -> pd.DataFrame:
        '''获取表字段信息'''
        return pd.DataFrame.from_dict(self._table_fields[table_name]).T

    def get_data_relations(self) -> pd.DataFrame:
        '''获取数据库链接信息（主键和外键）'''
        return pd.DataFrame(self.foreign_keys)

    def get_table_sample(self, table_name) -> pd.DataFrame:
        '''获取数据表样例'''
        return self._table_sample[table_name]

    def check_sql(self, sql) -> Union[bool, str]:
        '''检查sql是否合理

        参数
            sql: 待执行句子

        返回: 是否可以运行 报错信息
        '''
        try:
            self.conn.execute(text(sql))
            return True, 'ok'
        except:
            err_msg = traceback.format_exc()
            return False, err_msg

    def execute_sql(self, sql) -> bool:
        '''运行SQL'''
        result = self.conn.execute(text(sql))
        return list(result)

In [3]:
# DB_PATH 在 Cell 1 已定义；转换成 SQLAlchemy 的 sqlite URL
db_url = 'sqlite:///' + DB_PATH.replace('\\', '/')
parser = DBParser(db_url)

Table -> albums
Table -> artists
Table -> customers
Table -> employees
Table -> genres
Table -> invoice_items
Table -> invoices
Table -> media_types
Table -> playlist_track
Table -> playlists
Table -> tracks

In [4]:
parser.get_data_relations() #外键关系

   constrained_table constrained_columns referred_table referred_columns
0             albums          [ArtistId]        artists       [ArtistId]
1          customers      [SupportRepId]      employees     [EmployeeId]
2          employees         [ReportsTo]      employees     [EmployeeId]
3      invoice_items           [TrackId]         tracks        [TrackId]
4      invoice_items         [InvoiceId]       invoices      [InvoiceId]
5           invoices        [CustomerId]      customers     [CustomerId]
6     playlist_track           [TrackId]         tracks        [TrackId]
7     playlist_track        [PlaylistId]      playlists     [PlaylistId]
8             tracks       [MediaTypeId]    media_types    [MediaTypeId]
9             tracks           [GenreId]         genres        [GenreId]
10            tracks           [AlbumId]         albums        [AlbumId]

In [5]:
parser.get_table_sample("albums") #表样例

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1

In [6]:
parser.get_table_fields("genres") #字段画像

,name,type,nullable,default,primary_key,distinct,nan_count,max,min,random,mode
GenreId,GenreId,INTEGER,False,None,1,25,0,25,1,"[1, 4, 10]",NaN
Name,Name,NVARCHAR(120),True,None,0,25,0,World,Alternative,"[Rock And Roll, Soundtrack, Metal]",World

In [7]:
#模拟生成评测数据集

'''流程：
 1. 对每张表抽取 14 个候选字段组合（单字段 / 两两 / 三三）
 2. 对每个字段组合：
   - question_prompt → 生成问题
   - answer_prompt → 生成 SQL
   - check_sql 校验 SQL 可执行
   - execute_sql 执行，要求返回单行结果
   - question_rewrite_prompt → 问题口语化
   - answer_rewrite_prompt → 结果转自然语言
3. 追加到 gt_qes_answer = [question, table, sql, sql_result, nl_answer]'''

'流程：\n 1. 对每张表抽取 14 个候选字段组合（单字段 / 两两 / 三三）\n 2. 对每个字段组合：\n   - question_prompt → 生成问题\n   - answer_prompt → 生成 SQL\n   - check_sql 校验 SQL 可执行\n   - execute_sql 执行，要求返回单行结果\n   - question_rewrite_prompt → 问题口语化\n   - answer_rewrite_prompt → 结果转自然语言\n3. 追加到 gt_qes_answer = [question, table, sql, sql_result, nl_answer]'

In [8]:
# DeepSeek 调用封装
import time
import requests
from itertools import combinations
import numpy as np
from tqdm import tqdm

# ---------- DeepSeek 配置 ----------
API_KEY = "sk-2cde2196b86b428e8c2e714a7fc10151"   #  DeepSeek API Key
MODEL   = "deepseek-flash"                          # DeepSeek 官方模型名
URL     = "https://api.deepseek.com/chat/completions"


def ask_llm(question, nretry=5):
    """调用大模型（DeepSeek OpenAI 兼容接口）"""
    if nretry == 0:
        return None

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}",
    }
    data = {
        "model": MODEL,
        "temperature": 0.5,          # DeepSeek 用 temperature
        "messages": [{"role": "user", "content": question}],
    }
    try:
        response = requests.post(URL, headers=headers, json=data, timeout=30)
        return response.json()
    except Exception:
        return ask_llm(question, nretry - 1)

In [9]:
# 四个 prompt 模板 提示词模板
# 用户提问的生成
question_prompt = '''你是一个专业的数据库专家，现在需要从用户的角度提问模拟生成一个提问。提问是自然语言，且计数和统计类型的问题，请直接输出具体提问，不需要有其他输出：

表名称：{table_name}

需要提问和统计的字段：{field}

表{table_name}样例如下：
{data_sample_mk}

表{table_name} schema如下：
{data_schema}
'''

answer_prompt = '''你是一个专业的数据库专家，现在需要你结合表{table_name}的信息和提问，生成对应的SQL语句。请直接输出SQL，不需要有其他输出：

表名称：{table_name}

数据表样例如下：
{data_sample_mk}

数据表schema如下：
{data_schema}

提问：{question}
'''

question_rewrite_prompt = '''你是一个专业的数据库专家，现在需要从用户的角度提问模拟生成一个提问。现在需要你将的下面的提问，转换为用户提问的风格。请直接输出提问，不需要有其他输出，不要直接提到表明：

原始问题：{question}

查询的表：{table_name}
'''

answer_rewrite_prompt = '''你是一个专业的数据库专家，将下面的问题回答组织为自然语言。：

原始问题：{question}

执行SQL：{sql}

原始结果：{answer}
'''

In [ ]:
# 主循环
gt_qes_answer = []

# 对于每张表
for table_name in parser.table_names[:50]:
    # 表样例
    data_sample = parser.get_table_sample(table_name)
    data_sample_mk = data_sample.to_markdown()

    # 表格式
    data_schema = parser.get_table_fields(table_name).to_markdown()
    data_fields = list(data_sample.columns)

    # 待选字段
    candidate_fields = list(data_fields) + list(combinations(data_fields, 2)) + list(combinations(data_fields, 3))
    candidate_fields = [' 和 '.join(x) if isinstance(x, tuple) else x for x in candidate_fields]
    # 待选字段：小表自适应，大表维持原策略（前 20 抽 8 + 后段抽 6）
    head_pool = candidate_fields[:20]
    tail_pool = candidate_fields[20:]

    head = list(np.random.choice(head_pool, min(8, len(head_pool)), replace=False))
    tail = list(np.random.choice(tail_pool, min(6, len(tail_pool)), replace=False)) if tail_pool else []
    candidate_fields = head + tail

    # 对每个待选字段生成查询逻辑
    for field in tqdm(candidate_fields[:]):
        # 重试次数
        for _ in range(5):
            # 生成提问
            try:
                input_str = question_prompt.format(table_name=table_name, data_sample_mk=data_sample_mk, data_schema=data_schema, field=field)
                question = ask_llm(input_str)['choices'][0]['message']['content']

                # 生成答案SQL
                input_str = answer_prompt.format(table_name=table_name, data_sample_mk=data_sample_mk, data_schema=data_schema, question=question)
                answer = ask_llm(input_str)['choices'][0]['message']['content']
                answer = answer.strip('`').strip('\n').replace('sql\n', '')

                # 判断SQL是否符合逻辑
                flag, _ = parser.check_sql(answer)
                if not flag:
                    continue

                # 获取SQL答案
                sql_answer = parser.execute_sql(answer)
                if len(sql_answer) > 1:
                    continue
                sql_answer = sql_answer[0]
                sql_answer = ' '.join([str(x) for x in sql_answer])

                # 将提问改写，更加符合用户风格
                input_str = question_rewrite_prompt.format(question=question, table_name=table_name)
                question = ask_llm(input_str)['choices'][0]['message']['content']

                # 将SQL和结果改为自然语言
                input_str = answer_rewrite_prompt.format(question=question, sql=answer, answer=sql_answer)
                nl_answer = ask_llm(input_str)['choices'][0]['message']['content']

                gt_qes_answer.append([
                    question, table_name, answer, sql_answer, nl_answer
                ])
                break

            except Exception as e:
                print(f"\n[跳过] 表: {table_name} | 字段: {field} | 报错: {e}")
                continue

100%|██████████| 7/7 [02:16<00:00, 19.52s/it]
100%|██████████| 3/3 [00:28<00:00,  9.51s/it]
100%|██████████| 14/14 [05:50<00:00, 25.02s/it]
100%|██████████| 14/14 [05:46<00:00, 24.72s/it]
100%|██████████| 3/3 [00:48<00:00, 16.14s/it]
100%|██████████| 13/13 [04:52<00:00, 22.48s/it]
 71%|███████▏  | 10/14 [03:47<01:56, 29.15s/it]

In [27]:
import json

# 将评测数据集保存到本地文件
with open('eval_dataset.json', 'w', encoding='utf-8') as f:
    json.dump(gt_qes_answer, f, ensure_ascii=False, indent=4)
    
print("✅ 评测数据集已成功保存到 eval_dataset.json，共", len(gt_qes_answer), "条")

✅ 评测数据集已成功保存到 eval_dataset.json，共 49 条

In [13]:
import json

# 从本地文件读取评测数据集
with open('eval_dataset.json', 'r', encoding='utf-8') as f:
    gt_qes_answer = json.load(f)

print("✅ 成功加载评测数据集，共", len(gt_qes_answer), "条")

✅ 成功加载评测数据集，共 49 条

In [16]:
print("生成样本数：", len(gt_qes_answer))

# 展示前 5 条
for q, t, sql, res, nl in gt_qes_answer[:5]:
    print("=" * 60)
    print("表名   ：", t)
    print("问题   ：", q)
    print("SQL    ：", sql)
    print("SQL结果：", res)
    print("自然语言：", nl)

生成样本数： 49
============================================================
表名   ： albums
问题   ： albums 表里的 ArtistId 有多少个不同的值？
SQL    ： SELECT COUNT(DISTINCT ArtistId) FROM albums;
SQL结果： 204
自然语言： `albums` 表中 `ArtistId` 共有 **204 个不同的值**。
============================================================
表名   ： albums
问题   ： albums 表一共有多少条记录（按 AlbumId 统计）？Title 字段有多少个不同的专辑名称？
SQL    ： SELECT COUNT(AlbumId) AS 记录数, COUNT(DISTINCT Title) AS 不同专辑名称数 FROM albums;
SQL结果： 347 347
自然语言： `albums` 表按 `AlbumId` 统计共有 **347 条记录**；`Title` 字段共有 **347 个不同的专辑名称**。
============================================================
表名   ： albums
问题   ： albums 表里一共有多少个 AlbumId？
SQL    ： SELECT COUNT(AlbumId) FROM albums;
SQL结果： 347
自然语言： `albums` 表里一共有 **347** 个 `AlbumId`。
============================================================
表名   ： albums
问题   ： albums 表里 Title 字段一共有多少个不重复的专辑标题？
SQL    ： SELECT COUNT(DISTINCT Title) AS distinct_title_count FROM albums;
SQL结果： 347
自然语言： albums 表中 `Title` 字段共有 **347** 个不重复的专辑标题。
============================================================
表名   ： artists
问题   ： 一共有多少个不重复的艺术家名称？
SQL    ： SELECT COUNT(DISTINCT Name) FROM artists;
SQL结果： 275
自然语言： 一共有 **275** 个不重复的艺术家名称。

In [35]:
# Table选取和SQL生成
import os
from typing import Annotated
from agents import Agent, Runner, AsyncOpenAI, OpenAIChatCompletionsModel, function_tool

# ================= 定义工具 =================

@function_tool
def parse_table(table_name: Annotated[str, "The Table name"]) -> str:
    """Return field of the given table"""
    try:
        return parser.get_table_fields(table_name).to_markdown()
    except Exception as e:
        return f"获取表 {table_name} 失败，报错：{str(e)}"

@function_tool
def get_table_schema(table_name: Annotated[str, "The Table name"]) -> str:
    """Return detailed schema and sample data of the given table"""
    try:
        sample = parser.get_table_sample(table_name)
        sample_mk = sample.to_markdown() if not sample.empty else ""
        fields = parser.get_table_fields(table_name)
        # 截取关键信息防止 prompt 太长
        fields_mk = fields[['name', 'type', 'distinct', 'random']].to_markdown()
        return f"表名：{table_name}\n表结构：\n{fields_mk}\n\n数据样例：\n{sample_mk}"
    except Exception as e:
        return f"获取表 {table_name} 信息失败: {str(e)}"

# ================= 校验工具 =================
@function_tool
def validate_sql_tool(sql: Annotated[str, "The SQL query to validate"]) -> str:
    """Validate if the SQL is safe and executable. Return 'OK' if valid, else return the error message."""
    # 1. 安全检查：只允许 SELECT
    if not sql.strip().lower().startswith('select'):
        return "校验失败：只允许执行 SELECT 查询语句！"
    
    # 2. 语法和可执行性检查 (借用 parser 的 check_sql，但不返回数据，只验证)
    try:
        # 我们使用 SQLAlchemy 的 text() 包装执行一下看看，如果报错就捕获
        from sqlalchemy import text
        with parser.engine.connect() as conn:
            conn.execute(text(sql))
        return "OK"
    except Exception as e:
        return f"校验失败，数据库报错：{str(e)}"

# ================= 执行工具 =================
@function_tool
def execute_sql_tool(sql: Annotated[str, "The SQL query to execute"]) -> str:
    """Execute the SQL query and return the actual data result."""
    try:
        # 真正执行 SQL
        result = parser.execute_sql(sql)
        
        # 截断结果防止太长撑爆上下文，最多返回前 10 条结果
        if len(result) > 10:
            return f"{str(result[:10])}...（共 {len(result)} 条结果，已截断）"
        return str(result)
    except Exception as e:
        return f"执行报错：{str(e)}"

# ================= SQLAgent 类 =================

class SQLAgent:
    def __init__(self):
        self.client = AsyncOpenAI(
            api_key="sk-2cde2196b86b428e8c2e714a7fc10151",
            base_url="https://api.deepseek.com/v1"
        )
        self.model = OpenAIChatCompletionsModel(
            model="deepseek-flash",
            openai_client=self.client
        )

        # ---------- 1. Table 选取 Agent ----------
        self.think_agent = Agent(
            name="SQL Planer",
            instructions="你是一个专业的SQL专家，请分析在给定的表当中，哪一个表可以用来回答用户的问题。如果不知道表结构，可以调用工具查看。请直接输出表名。",
            model=self.model,
            tools=[parse_table]
        )
        
        # ----------2. SQL 生成 Agent ----------
        self.generate_agent = Agent(
            name="SQL Generator",
            instructions="""你是一个专业的 SQL 专家。你的任务是根据用户的问题和已经选定的表，生成对应的 SQLite 查询语句。
你可以使用 get_table_schema 工具查看表的详细结构和样例数据，以确保字段名和表名拼写正确。
请直接输出最终的 SQL 语句，不要包含 ```sql 标记，不要输出任何解释文字。""",
            model=self.model,
            tools=[get_table_schema]
        )
        
        # ---------- 3. 校验 Agent ----------
        self.validate_agent = Agent(
            name="SQL Validator",
            instructions="""你是一个专业的 SQL 校验专家。你需要使用 validate_sql_tool 工具来校验用户提供的 SQL 语句。
如果工具返回 'OK'，请直接输出 '校验通过'。
如果工具返回了报错信息，请直接输出该报错信息（不要添加任何多余的解释）。""",
            model=self.model,
            tools=[validate_sql_tool]
        )
        
        # ---------- 4. SQL 改写 Agent ----------
        self.rewrite_agent = Agent(
            name="SQL Rewriter",
            instructions="""你是一个专业的 SQL 改写专家。
用户之前生成的 SQL 报错了，你需要根据报错信息和用户问题，修正 SQL。
请直接输出修正后的、纯净的 SQLite 查询语句，不要包含 ```sql 标记，不要输出任何解释文字。""",
            model=self.model,
            tools=[]  # 改写不需要查数据库，纯推理即可
        )
        
        # ---------- 5. SQL 执行 Agent ----------
        self.execute_agent = Agent(
            name="SQL Executor",
            instructions="""你是一个专业的 SQL 执行专家。你需要使用 execute_sql_tool 工具执行用户提供的 SQL，并返回查询结果。
请直接输出工具返回的数据结果，不要添加多余的解释文字。""",
            model=self.model,
            tools=[execute_sql_tool]
        )

        # ---------- 6. 结果汇总 Agent ----------
        self.summary_agent = Agent(
            name="Result Summarizer",
            instructions="""你是一个专业的数据分析助手。
请根据用户的问题、执行的 SQL 以及查询返回的原始结果，用自然、简洁、流畅的中文回答用户的问题。
注意：如果原始结果为空，请直接告诉用户没有找到相关数据；如果结果是数值，请直接给出结论，不需要输出 SQL。""",
            model=self.model,
            tools=[]  # 无需工具
        )
        
    async def select_table(self, question):
        """第一步：Table 选取"""
        all_tables = ", ".join(parser.table_names)
        prompt = f"数据库中共有以下表：{all_tables}\n\n用户问题：{question}"
        result = await Runner.run(self.think_agent, prompt)
        return result.final_output

    async def generate_sql(self, question, selected_tables):
        """第二步：SQL生成"""
        prompt = f"已确定使用的表：{selected_tables}\n用户问题：{question}"
        result = await Runner.run(self.generate_agent, prompt)
        
        # 判空保护
        if not result.final_output:
            print("⚠️ 警告：模型生成 SQL 返回了空值")
            return ""
            
        # 简单清洗大模型可能带出的 markdown 标记
        import re
        sql = result.final_output.strip()
        sql = re.sub(r'^```(sql)?\n', '', sql, flags=re.IGNORECASE)
        sql = re.sub(r'\n```$', '', sql)
        return sql.strip()
        

    # ---------- SQL 校验方法 ----------
    async def validate_sql(self, sql):
        """第三步：SQL 校验"""
        prompt = f"请校验以下 SQL 语句：\n{sql}"
        result = await Runner.run(self.validate_agent, prompt)
        return result.final_output.strip()

    # ---------- SQL 改写方法 ----------
        # ---------- SQL 改写方法 ----------
    async def rewrite_sql(self, question, bad_sql, error_msg):
        """第四步：SQL 改写"""
        prompt = f"""用户问题：{question}

之前错误的 SQL：
{bad_sql}

数据库报错信息：
{error_msg}

请修正上述 SQL。"""
        result = await Runner.run(self.rewrite_agent, prompt)
        
        # 判空保护
        if not result.final_output:
            print("⚠️ 警告：模型改写 SQL 返回了空值")
            return ""
            
        # 简单清洗大模型可能带出的 markdown 标记
        import re
        fixed_sql = result.final_output.strip()
        fixed_sql = re.sub(r'^```(sql)?\n', '', fixed_sql, flags=re.IGNORECASE)
        fixed_sql = re.sub(r'\n```$', '', fixed_sql)
        return fixed_sql.strip()

    # ---------- SQL 执行方法 ----------
    async def execute_sql(self, sql):
        """第五步：SQL 执行"""
        prompt = f"请执行以下 SQL：\n{sql}"
        result = await Runner.run(self.execute_agent, prompt)
        return result.final_output.strip()

    # ---------- 结果汇总方法 ----------
    async def summarize_result(self, question, sql, result):
        """第六步：结果汇总（自然语言化）"""
        prompt = f"""用户问题：{question}

执行的 SQL：
{sql}

查询返回的原始结果：
{result}

请生成自然语言回答。"""
        
        summary_result = await Runner.run(self.summary_agent, prompt)
        return summary_result.final_output.strip() 

    # ---------- 一键式 ----------
    async def run_pipeline(self, question):
        """Pipeline：一键执行"""
        print(f"【用户提问】: {question}")
        
        # 1. 选表
        selected_tables = await self.select_table(question)
        print(f" 1. 选表完成: {selected_tables}")
        
        # 2. SQL 生成
        sql = await self.generate_sql(question, selected_tables)
        print(f" 2. SQL 生成:\n{sql}")
        
        # 3 & 4. 校验与改写（自纠错循环，最多重试 3 次）
        max_retries = 3
        for attempt in range(max_retries):
            # 校验
            val_result = await self.validate_sql(sql)
            
            if "校验通过" in val_result:
                print(f" 3. SQL 校验: 通过")
                break
            else:
                print(f" 3. SQL 校验失败 (尝试 {attempt+1}/{max_retries}): {val_result}")
                if attempt == max_retries - 1:
                    return {
                        "final_answer": "抱歉，生成的 SQL 多次校验失败，无法执行。",
                        "sql": sql, "raw_result": "执行报错", "selected_tables": selected_tables
                    }
                
                # 改写
                sql = await self.rewrite_sql(question, sql, val_result)
                print(f" 4. SQL 改写为:\n{sql}")
        
        # 5. SQL 执行
        raw_result = await self.execute_sql(sql)
        print(f" 5. SQL 执行结果: {raw_result}")
        
        # 6. 结果汇总
        final_answer = await self.summarize_result(question, sql, raw_result)
        print(f" 6. 自然语言回答: {final_answer}\n" + "-"*50)
        
        # 返回字典结构，专门为了后续评测
        return {
            "final_answer": final_answer,
            "sql": sql,
            "raw_result": raw_result,
            "selected_tables": selected_tables
        }

In [36]:
from tqdm import tqdm
import time

async def evaluate_pipeline(agent, dataset):
    table_correct = 0
    answer_correct = 0
    total = len(dataset)
    
    error_cases = []
    
    print(f"🎓 开始考试，共 {total} 道题...\n")
    
    for i, item in enumerate(dataset):
        question = item[0]       # 问题
        true_table = item[1]     # 标准表
        true_answer = str(item[3]).strip() # 标准结果
        
        print(f"\n[{i+1}/{total}] 正在处理: {question[:20]}...")
        
        try:
            # 1. 跑一遍完整的流水线
            result = await agent.run_pipeline(question)
            
            pred_tables = result["selected_tables"]
            pred_sql = result["sql"]
            
            # 2. 评估选表准确率
            if true_table in str(pred_tables):
                table_correct += 1
                table_ok = True
            else:
                table_ok = False
            
            # 3. 评估执行结果
            # 用 parser 重新跑一次纯数据
            try:
                data = parser.execute_sql(pred_sql)
                if len(data) > 0:
                    # 提取元组里的元素，拼成字符串
                    pred_answer = ' '.join([str(x) for x in data[0]]).strip()
                else:
                    pred_answer = ""
            except Exception as e:
                pred_answer = f"执行报错: {str(e)}"
                
            if pred_answer == true_answer:
                answer_correct += 1
                answer_ok = True
            else:
                answer_ok = False
                error_cases.append({
                    "question": question,
                    "true_table": true_table,
                    "pred_tables": pred_tables,
                    "true_answer": true_answer,
                    "pred_answer": pred_answer,
                    "pred_sql": pred_sql
                })
                
        except Exception as e:
            print(f"❌ 发生崩溃: {e}")
            continue

    # ================= 打印最终成绩单 =================
    print("\n" + "="*50)
    print("🏆 【最终评测成绩单】")
    print("="*50)
    print(f"测试总数: {total} 条")
    print(f"🎯 选表准确率: {table_correct}/{total} ({(table_correct/total)*100:.2f}%)")
    print(f"🎯 执行准确率: {answer_correct}/{total} ({(answer_correct/total)*100:.2f}%)")
    print("="*50)
    
    if error_cases:
        print(f"\n❌ 答错 {len(error_cases)} 条，前 3 条错题本如下：")
        for i, case in enumerate(error_cases[:3]):
            print(f"\n【错题 {i+1}】{case['question']}")
            print(f"标准表: {case['true_table']} | 预测表: {case['pred_tables']}")
            print(f"标准结果: {case['true_answer']}")
            print(f"预测结果: {case['pred_answer']}")
            print(f"错误 SQL: {case['pred_sql']}")
            
    return error_cases

# --- 开始考试 ---
# 实例化新的 Agent
agent = SQLAgent()

# 开始跑
errors = await evaluate_pipeline(agent, gt_qes_answer)

🎓 开始考试，共 49 道题...


[1/49] 正在处理: albums 表里的 ArtistId ...
【用户提问】: albums 表里的 ArtistId 有多少个不同的值？
 1. 选表完成: albums
 2. SQL 生成:
SELECT COUNT(DISTINCT ArtistId) FROM albums
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: 204
 6. 自然语言回答: albums 表中 ArtistId 共有 **204** 个不同的值。
--------------------------------------------------

[2/49] 正在处理: albums 表一共有多少条记录（按 A...
【用户提问】: albums 表一共有多少条记录（按 AlbumId 统计）？Title 字段有多少个不同的专辑名称？
 1. 选表完成: albums
 2. SQL 生成:
SELECT COUNT(AlbumId) AS AlbumCount, COUNT(DISTINCT Title) AS DistinctTitleCount FROM albums

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: | AlbumCount | DistinctTitleCount |
| --- | --- |
| 347 | 347 |
 6. 自然语言回答: albums 表共有 **347** 条记录，`Title` 字段有 **347** 个不同的专辑名称。
--------------------------------------------------

[3/49] 正在处理: albums 表里一共有多少个 Albu...
【用户提问】: albums 表里一共有多少个 AlbumId？
 1. 选表完成: albums

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 2. SQL 生成:
SELECT COUNT(AlbumId) FROM albums
 3. SQL 校验: 通过
 5. SQL 执行结果: ```
[(347,)]
```

[non-fatal] Tracing request failed

 6. 自然语言回答: albums 表中共有 **347** 个 AlbumId。
--------------------------------------------------

[4/49] 正在处理: albums 表里 Title 字段一共...
【用户提问】: albums 表里 Title 字段一共有多少个不重复的专辑标题？
 1. 选表完成: albums
 2. SQL 生成:
SELECT COUNT(DISTINCT Title) FROM albums;

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: 347
 6. 自然语言回答: albums 表中 Title 字段共有 **347** 个不重复的专辑标题。
--------------------------------------------------

[5/49] 正在处理: 一共有多少个不重复的艺术家名称？...
【用户提问】: 一共有多少个不重复的艺术家名称？
 1. 选表完成: artists
 2. SQL 生成:
SELECT COUNT(DISTINCT Name) FROM artists

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 3. SQL 校验: 通过
 5. SQL 执行结果: 275
 6. 自然语言回答: 一共有 **275** 个不重复的艺术家名称。
--------------------------------------------------

[6/49] 正在处理: 一共有多少个不重复的艺术家编号？...
【用户提问】: 一共有多少个不重复的艺术家编号？

[non-fatal] Tracing request failed

 1. 选表完成: artists
 2. SQL 生成:
SELECT COUNT(DISTINCT ArtistId) FROM artists;
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: 275
 6. 自然语言回答: 一共有 **275** 个不重复的艺术家编号。
--------------------------------------------------

[7/49] 正在处理: 帮我查一下 artists 表里不同的 ...
【用户提问】: 帮我查一下 artists 表里不同的 Name 有多少个，以及 ArtistId 一共有多少条记录，分别是多少？
 1. 选表完成: artists
 2. SQL 生成:
SELECT COUNT(DISTINCT Name) AS distinct_name_count, COUNT(ArtistId) AS artistid_count FROM artists

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 3. SQL 校验: 通过
 5. SQL 执行结果: | distinct_name_count | artistid_count |
|---------------------|----------------|
| 275                 | 275            |
 6. 自然语言回答: artists 表中共有 **275 个不同的 Name**，ArtistId 记录数也是 **275 条**。两者数量相同。
--------------------------------------------------

[8/49] 正在处理: 帮我查一下 customers 表里 C...
【用户提问】: 帮我查一下 customers 表里 Company 字段有多少条非空记录，以及去重后有多少个不同公司？

[non-fatal] Tracing request failed

 1. 选表完成: customers
 2. SQL 生成:
SELECT COUNT(Company) AS NonNullCompanyCount,
       COUNT(DISTINCT Company) AS DistinctCompanyCount
FROM customers
WHERE Company IS NOT NULL AND TRIM(Company) <> ''
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: Nonnullcompanycount | Distinctcompanycount
---|---
10 | 10
 6. 自然语言回答: 在 customers 表中，Company 字段共有 **10 条非空记录**（已排除 NULL 和空字符串），去重后得到 **10 个不同的公司**。这说明这 10 条非空记录中的公司名称各不相同，没有重复。
--------------------------------------------------

[9/49] 正在处理: LastName 这一列里一共有多少个不...
【用户提问】: LastName 这一列里一共有多少个不重复的姓氏？
 1. 选表完成: customers
 2. SQL 生成:
SELECT COUNT(DISTINCT LastName) FROM customers;

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 3. SQL 校验: 通过
 5. SQL 执行结果: 59
 6. 自然语言回答: LastName 这一列中共有 **59** 个不重复的姓氏。
--------------------------------------------------

[10/49] 正在处理: 帮我查一下 customers 表里 F...
【用户提问】: 帮我查一下 customers 表里 Fax 字段不为空的记录有多少条？
 1. 选表完成: customers

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(*) AS cnt
FROM customers
WHERE Fax IS NOT NULL AND TRIM(Fax) <> ''
 3. SQL 校验: 通过
 5. SQL 执行结果: 查询结果：

| cnt |
|-----|
| 12  |

符合条件的记录数为 **12** 条。
 6. 自然语言回答: customers 表中 Fax 字段不为空的记录共有 **12** 条。
--------------------------------------------------

[11/49] 正在处理: 客户表里有多少个不重复的电话号码？...
【用户提问】: 客户表里有多少个不重复的电话号码？

[non-fatal] Tracing request failed

 1. 选表完成: customers
 2. SQL 生成:
SELECT COUNT(DISTINCT Phone) FROM customers;
 3. SQL 校验: 通过
 5. SQL 执行结果: 58
 6. 自然语言回答: 客户表中不重复的电话号码共有 **58 个**。
--------------------------------------------------

[12/49] 正在处理: 帮我统计一下 customers 表里，...
【用户提问】: 帮我统计一下 customers 表里，FirstName、LastName 和 Address 的不同组合分别有多少客户？

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 1. 选表完成: customers
 2. SQL 生成:
SELECT FirstName, LastName, Address, COUNT(*) AS CustomerCount
FROM customers
GROUP BY FirstName, LastName, Address;
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: FirstName | LastName | Address | CustomerCount
---|---|---|---
Aaron | Mitchell | 696 Osborne Street | 1
Alexandre | Rocha | Av. Paulista, 2022 | 1
Astrid | Gruber | Rotenturmstraße 4, 1010 Innere Stadt | 1
Bjørn | Hansen | Ullevålsveien 14 | 1
Camille | Bernard | 4, Rue Milton | 1
Daan | Peeters | Grétrystraat 63 | 1
Dan | Miller | 541 Del Medio Avenue | 1
Diego | Gutiérrez | 307 Macacha Güemes | 1
Dominique | Lefebvre | 8, Rue Hanovre | 1
Eduardo | Martins | Rua Dr. Falcão Filho, 155 | 1

（共 59 条结果，已截断）
 6. 自然语言回答: 按 FirstName、LastName 和 Address 分组统计后，共得到 **59 个不同的组合**。从查询结果看，每个组合对应的客户数均为 **1**，即每个“姓名 + 地址”组合下各有 1 名客户。由于结果较多已截断，以上为基于返回结果的汇总结论。
--------------------------------------------------

[13/49] 正在处理: 帮我查一下 customers 表里 L...
【用户提问】: 帮我查一下 customers 表里 LastName、PostalCode 和 Email 分别有多少个不重复的值？
 1. 选表完成: customers

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(DISTINCT LastName) AS LastName_count, COUNT(DISTINCT PostalCode) AS PostalCode_count, COUNT(DISTINCT Email) AS Email_count FROM customers;
 3. SQL 校验: 通过
 5. SQL 执行结果: | LastName_count | PostalCode_count | Email_count |
|----------------|------------------|-------------|
| 59 | 55 | 59 |
 6. 自然语言回答: 在 customers 表中：

- **LastName** 有 59 个不重复的值
- **PostalCode** 有 55 个不重复的值
- **Email** 有 59 个不重复的值
--------------------------------------------------

[14/49] 正在处理: 你能帮我统计一下 customers 表...
【用户提问】: 你能帮我统计一下 customers 表中 FirstName、State 和 Phone 三个字段都不为空的客户数量吗？

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 1. 选表完成: customers
 2. SQL 生成:
SELECT COUNT(*) FROM customers WHERE FirstName IS NOT NULL AND FirstName <> '' AND State IS NOT NULL AND State <> '' AND Phone IS NOT NULL AND Phone <> '';
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: 查询结果：**30**
 6. 自然语言回答: 统计结果显示，customers 表中 FirstName、State 和 Phone 三个字段都不为空的客户共有 **30** 位。
--------------------------------------------------

[15/49] 正在处理: 帮我统计一下员工编号一共有多少个，以及名...
【用户提问】: 帮我统计一下员工编号一共有多少个，以及名字去重后有多少个不同的，可以吗？
 1. 选表完成: employees

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(EmployeeId) AS EmployeeCount, COUNT(DISTINCT FirstName || ' ' || LastName) AS DistinctNameCount FROM employees
 3. SQL 校验: 通过
 5. SQL 执行结果: [(8, 8)]
 6. 自然语言回答: 可以的。统计结果如下：

- **员工编号总数**：8 个
- **姓名去重后的人数**：8 个

两个数值一致，说明这 8 条员工记录中，每个员工编号对应的姓名都是唯一的，没有重名的情况。
--------------------------------------------------

[16/49] 正在处理: employees 表里每个 Count...
【用户提问】: employees 表里每个 Country 分别有多少员工？帮我按员工人数从多到少排一下。

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 1. 选表完成: employees
 2. SQL 生成:
SELECT Country, COUNT(*) AS EmployeeCount
FROM employees
GROUP BY Country
ORDER BY EmployeeCount DESC
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: | Country | EmployeeCount |
|---------|---------------|
| Canada  | 8             |
 6. 自然语言回答: employees 表中目前只有一个国家有记录：**Canada（加拿大）**，共有 **8 名员工**。

由于其他国家的数据为空，所以按员工人数从多到少排序后只显示这一条。
--------------------------------------------------

[17/49] 正在处理: employees 表里的 Phone ...
【用户提问】: employees 表里的 Phone 字段一共有多少个不同的电话号码？
 1. 选表完成: employees
 2. SQL 生成:
SELECT COUNT(DISTINCT Phone) AS distinct_phone_count FROM employees;

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: distinct_phone_count
7
 6. 自然语言回答: employees 表中 Phone 字段一共有 7 个不同的电话号码。
--------------------------------------------------

[18/49] 正在处理: employees 表里 Fax 字段有...
【用户提问】: employees 表里 Fax 字段有多少条非空记录？

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 1. 选表完成: employees
 2. SQL 生成:
SELECT COUNT(*) AS NonNullFaxCount FROM employees WHERE Fax IS NOT NULL AND Fax != '';
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: | NonNullFaxCount |
|-----------------|
| 8 |
 6. 自然语言回答: employees 表里 Fax 字段共有 8 条非空记录。
--------------------------------------------------

[19/49] 正在处理: 帮我查一下 employees 表里 B...
【用户提问】: 帮我查一下 employees 表里 BirthDate 在 1960 年到 1980 年之间的员工有多少人？按 EmployeeId 统计。
 1. 选表完成: employees
 2. SQL 生成:
SELECT COUNT(EmployeeId) AS EmployeeCount
FROM employees
WHERE BirthDate >= '1960-01-01'
  AND BirthDate < '1981-01-01';

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: | EmployeeCount |
|---|
| 6 |
 6. 自然语言回答: 共有 **6 名员工**的 BirthDate 在 1960 年到 1980 年之间（按 EmployeeId 统计）。
--------------------------------------------------

[20/49] 正在处理: employees 表里有多少个不重复的...
【用户提问】: employees 表里有多少个不重复的 Email 地址？
 1. 选表完成: employees
 2. SQL 生成:
SELECT COUNT(DISTINCT Email) AS distinct_email_count FROM employees

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 3. SQL 校验: 通过
 5. SQL 执行结果: distinct_email_count
8
 6. 自然语言回答: employees 表中共有 **8** 个不重复的 Email 地址。
--------------------------------------------------

[21/49] 正在处理: 帮我统计一下 employees 表里员...
【用户提问】: 帮我统计一下 employees 表里员工编号总共有多少条，并分别看看 BirthDate 和 Address 有多少条非空值、各有多少个不同取值。

[non-fatal] Tracing request failed

 1. 选表完成: employees
 2. SQL 生成:
SELECT COUNT(EmployeeId) AS total_employee_count,
       COUNT(BirthDate) AS birthdate_non_null_count,
       COUNT(DISTINCT BirthDate) AS birthdate_distinct_count,
       COUNT(Address) AS address_non_null_count,
       COUNT(DISTINCT Address) AS address_distinct_count
FROM employees
 3. SQL 校验: 通过
 5. SQL 执行结果: | total_employee_count | birthdate_non_null_count | birthdate_distinct_count | address_non_null_count | address_distinct_count |
|---|---|---|---|---|
| 8 | 8 | 8 | 8 | 8 |

[non-fatal] Tracing request failed

 6. 自然语言回答: employees 表中共有 **8 条员工编号记录**。

其中：
- **BirthDate**：非空值 **8 条**，不同取值 **8 个**
- **Address**：非空值 **8 条**，不同取值 **8 个**

也就是说，这两列当前都没有空值，且每个员工的 BirthDate 和 Address 取值都互不相同。
--------------------------------------------------

[22/49] 正在处理: 帮我按州统计一下 employees 表...
【用户提问】: 帮我按州统计一下 employees 表里每个州的员工人数，以及出生日期涉及的不同年份数量和不同电话号码数量。
 1. 选表完成: employees
 2. SQL 生成:
SELECT State,
       COUNT(*) AS employee_count,
       COUNT(DISTINCT strftime('%Y', BirthDate)) AS distinct_birth_years,
       COUNT(DISTINCT Phone) AS distinct_phone_count
FROM employees
GROUP BY State;
 3. SQL 校验: 通过

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 5. SQL 执行结果: | State | employee_count | distinct_birth_years | distinct_phone_count |
|-------|----------------|----------------------|----------------------|
| AB    | 8              | 7                    | 7                    |
 6. 自然语言回答: 按州统计后，仅返回了 **AB 州** 的数据：

- 员工人数：**8 人**
- 出生日期涉及的不同年份数量：**7 个**
- 不同电话号码数量：**7 个**
--------------------------------------------------

[23/49] 正在处理: 帮我查一下 genres 表里 Genr...
【用户提问】: 帮我查一下 genres 表里 GenreId 和 Name 分别有多少条非空记录，以及它们各有多少个不同的取值。
 1. 选表完成: genres

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(GenreId) AS GenreId_非空记录数, COUNT(DISTINCT GenreId) AS GenreId_不同取值数, COUNT(Name) AS Name_非空记录数, COUNT(DISTINCT Name) AS Name_不同取值数 FROM genres
 3. SQL 校验: 通过
 5. SQL 执行结果: | GenreId_非空记录数 | GenreId_不同取值数 | Name_非空记录数 | Name_不同取值数 |
|---|---|---|---|
| 25 | 25 | 25 | 25 |
 6. 自然语言回答: 在 `genres` 表中：

- `GenreId`：非空记录数为 **25**，不同取值数为 **25**
- `Name`：非空记录数为 **25**，不同取值数为 **25**

也就是说，这两列都没有空值，且各列中的 25 条记录取值全部不重复。
--------------------------------------------------

[24/49] 正在处理: genres 表里 Name 字段有多少...
【用户提问】: genres 表里 Name 字段有多少种不同的音乐类型名称？

[non-fatal] Tracing request failed

 1. 选表完成: genres
 2. SQL 生成:
SELECT COUNT(DISTINCT Name) AS NameCount FROM genres
 3. SQL 校验: 通过
 5. SQL 执行结果: | NameCount |
|-----------|
| 25 |
 6. 自然语言回答: genres 表中 Name 字段共有 **25** 种不同的音乐类型名称。
--------------------------------------------------

[25/49] 正在处理: genres表里一共有多少个GenreI...
【用户提问】: genres表里一共有多少个GenreId？

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 1. 选表完成: genres
 2. SQL 生成:
SELECT COUNT(GenreId) AS genre_count FROM genres
 3. SQL 校验: 通过
 5. SQL 执行结果: 2025

[non-fatal] Tracing request failed

 6. 自然语言回答: genres 表中一共有 2025 个 GenreId。
--------------------------------------------------

[26/49] 正在处理: 帮我查一下 invoice_items ...
【用户提问】: 帮我查一下 invoice_items 表总共有多少条记录，并算一下所有记录里 UnitPrice 与 Quantity 相乘后的总和，以及 Quantity 的总和。
 1. 选表完成: invoice_items
 2. SQL 生成:
SELECT COUNT(*) AS total_records, SUM(UnitPrice * Quantity) AS total_amount, SUM(Quantity) AS total_quantity FROM invoice_items
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: | total_records | total_amount | total_quantity |
|---------------|--------------|----------------|
| 2240          | 2328.6       | 2240           |
 6. 自然语言回答: invoice_items 表共有 2,240 条记录。所有记录中 UnitPrice × Quantity 的总和为 2,328.6，Quantity 的总和为 2,240。
--------------------------------------------------

[27/49] 正在处理: 帮我查一下 invoice_items ...
【用户提问】: 帮我查一下 invoice_items 表里 UnitPrice 等于 0.99 的记录有多少条？
 1. 选表完成: invoice_items
 2. SQL 生成:
SELECT COUNT(*) FROM invoice_items WHERE UnitPrice = 0.99;
 3. SQL 校验: 通过

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 5. SQL 执行结果: 2129
 6. 自然语言回答: invoice_items 表中 UnitPrice 等于 0.99 的记录共有 **2129 条**。
--------------------------------------------------

[28/49] 正在处理: 我想查一下 invoice_items ...
【用户提问】: 我想查一下 invoice_items 表里总共有多少条 InvoiceLineId，这些明细对应多少个不同的 InvoiceId？
 1. 选表完成: invoice_items

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(InvoiceLineId) AS InvoiceLineCount,
       COUNT(DISTINCT InvoiceId) AS InvoiceCount
FROM invoice_items
 3. SQL 校验: 通过
 5. SQL 执行结果: | InvoiceLineCount | InvoiceCount |
|------------------|--------------|
| 2240 | 412 |
 6. 自然语言回答: invoice_items 表中共有 **2,240** 条 InvoiceLineId 明细，这些明细对应 **412** 个不同的 InvoiceId。
--------------------------------------------------

[29/49] 正在处理: 帮我统计一下 invoice_items...
【用户提问】: 帮我统计一下 invoice_items 里有多少个不同的 InvoiceId，并算算这些记录的 UnitPrice 总和和平均值。

[non-fatal] Tracing request failed

 1. 选表完成: invoice_items
 2. SQL 生成:
SELECT COUNT(DISTINCT InvoiceId) AS distinct_invoice_count, SUM(UnitPrice) AS total_unit_price, AVG(UnitPrice) AS avg_unit_price FROM invoice_items;
 3. SQL 校验: 通过
 5. SQL 执行结果: | distinct_invoice_count | total_unit_price | avg_unit_price |
|------------------------|------------------|----------------|
| 412 | 2328.6 | 1.0395535714285713 |

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 6. 自然语言回答: invoice_items 中共有 **412 个不同的 InvoiceId**。
这些记录的 UnitPrice **总和为 2328.6**，**平均值为约 1.0396**。
--------------------------------------------------

[30/49] 正在处理: 帮我查一下 invoice_items ...
【用户提问】: 帮我查一下 invoice_items 里一共有多少条发票明细（按 InvoiceLineId 统计），这些明细的 Quantity 总和是多少？
 1. 选表完成: invoice_items
 2. SQL 生成:
SELECT COUNT(InvoiceLineId) AS TotalLines, SUM(Quantity) AS TotalQuantity FROM invoice_items

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: | TotalLines | TotalQuantity |
|------------|---------------|
| 2240       | 2240          |
 6. 自然语言回答: invoice_items 中共有 **2,240 条**发票明细（按 InvoiceLineId 统计），这些明细的 Quantity 总和为 **2,240**。
--------------------------------------------------

[31/49] 正在处理: 帮我查一下 invoice_items ...
【用户提问】: 帮我查一下 invoice_items 表：统计不同 InvoiceLineId 有多少个，并算一下 UnitPrice 的总和、平均值、最大值、最小值，以及 Quantity 的总和、平均值、最大值、最小值。
 1. 选表完成: invoice_items

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(DISTINCT InvoiceLineId) AS InvoiceLineId_count,
       SUM(UnitPrice) AS UnitPrice_sum,
       AVG(UnitPrice) AS UnitPrice_avg,
       MAX(UnitPrice) AS UnitPrice_max,
       MIN(UnitPrice) AS UnitPrice_min,
       SUM(Quantity) AS Quantity_sum,
       AVG(Quantity) AS Quantity_avg,
       MAX(Quantity) AS Quantity_max,
       MIN(Quantity) AS Quantity_min
FROM invoice_items;
 3. SQL 校验: 通过
 5. SQL 执行结果: | InvoiceLineId_count | UnitPrice_sum | UnitPrice_avg | UnitPrice_max | UnitPrice_min | Quantity_sum | Quantity_avg | Quantity_max | Quantity_min |
|---|---|---|---|---|---|---|---|---|
| 2240 | 2328.6 | 1.0395535714285713 | 1.99 | 0.99 | 2240 | 1.0 | 1 | 1 |
 6. 自然语言回答: 查询结果如下：

- 不同 `InvoiceLineId` 的数量：**2240**
- `UnitPrice`：
  - 总和：**2328.6**
  - 平均值：**约 1.0396**
  - 最大值：**1.99**
  - 最小值：**0.99**
- `Quantity`：
  - 总和：**2240**
  - 平均值：**1.0**
  - 最大值：**1**
  - 最小值：**1**

可以看出，`Quantity` 所有记录均为 **1**。
--------------------------------------------------

[32/49] 正在处理: 这个表里一共有多少张发票？...
【用户提问】: 这个表里一共有多少张发票？

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 1. 选表完成: invoices
 2. SQL 生成:
SELECT COUNT(*) AS invoice_count FROM invoices;
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: 查询结果：

| invoice_count |
|---------------|
| 412 |
 6. 自然语言回答: 这个表里一共有 412 张发票。
--------------------------------------------------

[33/49] 正在处理: invoices 表里不同 Custom...
【用户提问】: invoices 表里不同 CustomerId 有多少个？我想知道一共有多少个不同的客户产生过发票。
 1. 选表完成: invoices
 2. SQL 生成:
SELECT COUNT(DISTINCT CustomerId) AS CustomerCount FROM invoices

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: | CustomerCount |
|---------------|
| 59 |
 6. 自然语言回答: invoices 表中共有 **59 个不同的 CustomerId**，即一共有 **59 个不同的客户**产生过发票。
--------------------------------------------------

[34/49] 正在处理: 能帮我查一下发票总共有多少张，所有发票加...
【用户提问】: 能帮我查一下发票总共有多少张，所有发票加起来一共多少钱吗？
 1. 选表完成: invoices
 2. SQL 生成:
SELECT COUNT(*) AS InvoiceCount, SUM(Total) AS TotalAmount
FROM invoices;

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 3. SQL 校验: 通过
 5. SQL 执行结果: | InvoiceCount | TotalAmount |
|--------------|-------------|
| 412          | 2328.6      |
 6. 自然语言回答: 共有 **412 张发票**，所有发票金额合计为 **2328.6**。
--------------------------------------------------

[35/49] 正在处理: 帮我统计一下每个账单地址对应有多少张发票...
【用户提问】: 帮我统计一下每个账单地址对应有多少张发票（按 InvoiceId 计数），并告诉我开票数量最多的账单地址是哪个、对应多少张发票。

[non-fatal] Tracing request failed

 1. 选表完成: invoices
 2. SQL 生成:
SELECT BillingAddress, COUNT(InvoiceId) AS InvoiceCount
FROM invoices
GROUP BY BillingAddress
ORDER BY InvoiceCount DESC;
 3. SQL 校验: 通过
 5. SQL 执行结果: | BillingAddress | InvoiceCount |
|---|---|
| Via Degli Scipioni, 43 | 7 |
| Ullevålsveien 14 | 7 |
| Theodor-Heuss-Straße 34 | 7 |
| Tauentzienstraße 8 | 7 |
| Sønder Boulevard 51 | 7 |
| Rua dos Campeões Europeus de Viena, 4350 | 7 |
| Rua da Assunção 53 | 7 |
| Rua Dr. Falcão Filho, 155 | 7 |
| Rotenturmstraße 4, 1010 Innere Stadt | 7 |
| Rilská 3174/6 | 7 |

（共 59 条结果，已截断）

[non-fatal] Tracing request failed

 6. 自然语言回答: 按账单地址统计发票数量后，开票数量最多的是 **7 张发票**。

查询结果按发票数量降序排列，前 10 个账单地址均为 **7 张**，因此目前看到的是多个地址并列最多，包括：

- Via Degli Scipioni, 43
- Ullevålsveien 14
- Theodor-Heuss-Straße 34
- Tauentzienstraße 8
- Sønder Boulevard 51
- Rua dos Campeões Europeus de Viena, 4350
- Rua da Assunção 53
- Rua Dr. Falcão Filho, 155
- Rotenturmstraße 4, 1010 Innere Stadt
- Rilská 3174/6

由于结果共 59 条且已截断，无法确认是否还有其他地址同样为 7 张；但可以确定最高开票数量为 **7 张**，且不是唯一地址。
--------------------------------------------------

[36/49] 正在处理: 帮我查一下 media_types 表里...
【用户提问】: 帮我查一下 media_types 表里 MediaTypeId 总共有多少条，以及不同的 MediaTypeId 有多少个？
 1. 选表完成: media_types
 2. SQL 生成:
SELECT COUNT(MediaTypeId) AS total_count, COUNT(DISTINCT MediaTypeId) AS distinct_count FROM media_types

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 3. SQL 校验: 通过
 5. SQL 执行结果: total_count：5，distinct_count：5
 6. 自然语言回答: media_types 表中共有 5 条 MediaTypeId 记录，其中不同的 MediaTypeId 有 5 个。
--------------------------------------------------

[37/49] 正在处理: 帮我统计一下 media_types 表...
【用户提问】: 帮我统计一下 media_types 表里 MediaTypeId 的总记录数，以及 Name 字段去重后有多少个不同的名称？
 1. 选表完成: media_types

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(MediaTypeId) AS total_records, COUNT(DISTINCT Name) AS distinct_names FROM media_types;
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: | total_records | distinct_names |
|---------------|----------------|
| 5             | 5              |
 6. 自然语言回答: media_types 表中 MediaTypeId 的总记录数为 **5** 条；Name 字段去重后有 **5** 个不同的名称。
--------------------------------------------------

[38/49] 正在处理: media_types 表里的 Name...
【用户提问】: media_types 表里的 Name 字段一共有多少种不同的媒体类型名称？
 1. 选表完成: media_types
 2. SQL 生成:
SELECT COUNT(DISTINCT Name) FROM media_types
 3. SQL 校验: 通过

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 5. SQL 执行结果: 5
 6. 自然语言回答: media_types 表里的 Name 字段一共有 **5** 种不同的媒体类型名称。
--------------------------------------------------

[39/49] 正在处理: playlist_track 表里一共有...
【用户提问】: playlist_track 表里一共有多少个不重复的 TrackId？
 1. 选表完成: playlist_track

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(DISTINCT TrackId) FROM playlist_track
 3. SQL 校验: 通过
 5. SQL 执行结果: 3503
 6. 自然语言回答: playlist_track 表中共有 **3503** 个不重复的 TrackId。
--------------------------------------------------

[40/49] 正在处理: playlist_track 表里一共有...
【用户提问】: playlist_track 表里一共有多少个不重复的 PlaylistId？

[non-fatal] Tracing request failed

 1. 选表完成: playlist_track
 2. SQL 生成:
SELECT COUNT(DISTINCT PlaylistId) FROM playlist_track;
 3. SQL 校验: 通过

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 5. SQL 执行结果: 14
 6. 自然语言回答: playlist_track 表中一共有 14 个不重复的 PlaylistId。
--------------------------------------------------

[41/49] 正在处理: playlists 表里一共有多少个 P...
【用户提问】: playlists 表里一共有多少个 PlaylistId？
 1. 选表完成: playlists
 2. SQL 生成:
SELECT COUNT(PlaylistId) FROM playlists

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: 18
 6. 自然语言回答: playlists 表中共有 **18** 个 PlaylistId。
--------------------------------------------------

[42/49] 正在处理: playlists 表里一共有多少个不重...
【用户提问】: playlists 表里一共有多少个不重复的播放列表名称？

[non-fatal] Tracing request failed

 1. 选表完成: playlists
 2. SQL 生成:
SELECT COUNT(DISTINCT Name) AS distinct_playlist_names FROM playlists;
 3. SQL 校验: 通过
 5. SQL 执行结果: distinct_playlist_names
----------------------
14
 6. 自然语言回答: playlists 表中共有 **14** 个不重复的播放列表名称。
--------------------------------------------------

[43/49] 正在处理: playlists 表里 Playlis...
【用户提问】: playlists 表里 PlaylistId 和 Name 分别有多少个不重复的值？

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 1. 选表完成: playlists
 2. SQL 生成:
SELECT COUNT(DISTINCT PlaylistId) AS PlaylistId_count, COUNT(DISTINCT Name) AS Name_count FROM playlists;

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: | PlaylistId_count | Name_count |
|---|---|
| 18 | 14 |
 6. 自然语言回答: 在 playlists 表中，PlaylistId 有 18 个不重复的值，Name 有 14 个不重复的值。
--------------------------------------------------

[44/49] 正在处理: tracks 里作曲者为空的曲目有多少首...
【用户提问】: tracks 里作曲者为空的曲目有多少首？
 1. 选表完成: tracks

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(*) AS TrackCount
FROM tracks
WHERE Composer IS NULL OR TRIM(Composer) = '';
 3. SQL 校验: 通过
 5. SQL 执行结果: 查询结果：

| TrackCount |
|------------|
| 978 |
 6. 自然语言回答: tracks 表中作曲者为空的曲目共有 **978** 首。
--------------------------------------------------

[45/49] 正在处理: 价格是 0.99 的歌曲一共有多少首？...
【用户提问】: 价格是 0.99 的歌曲一共有多少首？

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 1. 选表完成: tracks
 2. SQL 生成:
SELECT COUNT(*) AS track_count FROM tracks WHERE UnitPrice = 0.99

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: | track_count |
|-------------|
| 3290 |
 6. 自然语言回答: 价格为 0.99 的歌曲共有 **3290 首**。
--------------------------------------------------

[46/49] 正在处理: tracks 里一共有多少首曲目（按 T...
【用户提问】: tracks 里一共有多少首曲目（按 TrackId 数量统计）？这些曲目的 Bytes 总和、平均值、最大值和最小值分别是多少？
 1. 选表完成: tracks
 2. SQL 生成:
SELECT COUNT(TrackId) AS TrackCount, SUM(Bytes) AS TotalBytes, AVG(Bytes) AS AvgBytes, MAX(Bytes) AS MaxBytes, MIN(Bytes) AS MinBytes FROM tracks

[non-fatal] Tracing request failed

 3. SQL 校验: 通过
 5. SQL 执行结果: | TrackCount | TotalBytes | AvgBytes | MaxBytes | MinBytes |
|---|---|---|---|---|
| 3503 | 117386255350 | 33510207.065372538 | 1059546140 | 38747 |
 6. 自然语言回答: tracks 表中共有 **3503** 首曲目（按 TrackId 统计）。

这些曲目的 Bytes 数据如下：
- **总和**：117,386,255,350 字节
- **平均值**：约 33,510,207.07 字节
- **最大值**：1,059,546,140 字节
- **最小值**：38,747 字节
--------------------------------------------------

[47/49] 正在处理: 帮我统计一下 tracks 中有作曲家信...
【用户提问】: 帮我统计一下 tracks 中有作曲家信息的曲目数量，并计算这些曲目的总时长（Milliseconds 之和）和总字节数（Bytes 之和）。
 1. 选表完成: tracks

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 2. SQL 生成:
SELECT COUNT(*) AS TrackCount,
       SUM(Milliseconds) AS TotalMilliseconds,
       SUM(Bytes) AS TotalBytes
FROM tracks
WHERE Composer IS NOT NULL AND TRIM(Composer) <> ''
 3. SQL 校验: 通过
 5. SQL 执行结果: | TrackCount | TotalMilliseconds | TotalBytes |
|---|---|---|
| 2525 | 682937390 | 21642965876 |

[non-fatal] Tracing request failed

 6. 自然语言回答: 在 tracks 表中，有作曲家信息（Composer 非空且去除空格后不为空）的曲目共有 **2,525 首**。

这些曲目的合计数据为：
- 总时长：**682,937,390 毫秒**（约 **189.7 小时**，约 **7.9 天**）
- 总字节数：**21,642,965,876 Bytes**（约 **20.16 GB**）
--------------------------------------------------

[48/49] 正在处理: tracks 表里有多少首不同名称的歌曲...
【用户提问】: tracks 表里有多少首不同名称的歌曲？这些歌曲的 Bytes 总和是多少？
 1. 选表完成: tracks

[non-fatal] Tracing request failed

 2. SQL 生成:
SELECT COUNT(DISTINCT Name) AS song_count, SUM(Bytes) AS total_bytes
FROM (
    SELECT Name, MAX(Bytes) AS Bytes
    FROM tracks
    GROUP BY Name
)
 3. SQL 校验: 通过
 5. SQL 执行结果: song_count: 3257
total_bytes: 113472137806
 6. 自然语言回答: tracks 表中共有 **3,257** 首不同名称的歌曲，这些歌曲的 Bytes 总和为 **113,472,137,806** 字节（约 113.5 GB）。
--------------------------------------------------

[49/49] 正在处理: tracks 表里一共有多少首歌（按 T...
【用户提问】: tracks 表里一共有多少首歌（按 TrackId 计数）？另外，所有歌曲的 Milliseconds 和 Bytes 的总和、平均值、最大值、最小值分别是多少？

[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.

 1. 选表完成: tracks
 2. SQL 生成:
SELECT COUNT(TrackId) AS TrackCount,
       SUM(Milliseconds) AS SumMilliseconds,
       AVG(Milliseconds) AS AvgMilliseconds,
       MAX(Milliseconds) AS MaxMilliseconds,
       MIN(Milliseconds) AS MinMilliseconds,
       SUM(Bytes) AS SumBytes,
       AVG(Bytes) AS AvgBytes,
       MAX(Bytes) AS MaxBytes,
       MIN(Bytes) AS MinBytes
FROM tracks
 3. SQL 校验: 通过

[non-fatal] Tracing request failed

 5. SQL 执行结果: 查询结果：

| TrackCount | SumMilliseconds | AvgMilliseconds | MaxMilliseconds | MinMilliseconds | SumBytes | AvgBytes | MaxBytes | MinBytes |
|---|---|---|---|---|---|---|---|---|
| 3503 | 1378778040 | 393599.2121039109 | 5286953 | 1071 | 117386255350 | 33510207.065372538 | 1059546140 | 38747 |
 6. 自然语言回答: tracks 表按 TrackId 计数共有 **3503 首歌**。

- **Milliseconds（毫秒）**：总和 1,378,778,040；平均值约 393,599.21；最大值 5,286,953；最小值 1,071。
- **Bytes（字节）**：总和 117,386,255,350；平均值约 33,510,207.07；最大值 1,059,546,140；最小值 38,747。
--------------------------------------------------

==================================================
🏆 【最终评测成绩单】
==================================================
测试总数: 49 条
🎯 选表准确率: 49/49 (100.00%)
🎯 执行准确率: 47/49 (95.92%)
==================================================

❌ 答错 2 条，前 3 条错题本如下：

【错题 1】帮我统计一下 customers 表里，FirstName、LastName 和 Address 的不同组合分别有多少客户？
标准表: customers | 预测表: customers
标准结果: 59
预测结果: Aaron Mitchell 696 Osborne Street 1
错误 SQL: SELECT FirstName, LastName, Address, COUNT(*) AS CustomerCount
FROM customers
GROUP BY FirstName, LastName, Address;

【错题 2】tracks 表里有多少首不同名称的歌曲？这些歌曲的 Bytes 总和是多少？
标准表: tracks | 预测表: tracks
标准结果: 3257 117386255350
预测结果: 3257 113472137806
错误 SQL: SELECT COUNT(DISTINCT Name) AS song_count, SUM(Bytes) AS total_bytes
FROM (
    SELECT Name, MAX(Bytes) AS Bytes
    FROM tracks
    GROUP BY Name
)

[non-fatal] Tracing request failed
[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.
[non-fatal] Tracing request failed
[non-fatal] Tracing request failed
[non-fatal] Tracing request failed
[non-fatal] Tracing: max retries reached, giving up on this batch.